force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>The object is created to log the errors occured during future method or any such background operation. Although, this object is useful generally for all kind of error logging.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>This field is used to store the name of the class where the error occurred.</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field is used to store the error message in case of exception.</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>This field stores the line number where the exception occured.</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>This field stores the name of the method where the exception occourred.</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field stored the ID of the record which was being processed when the error occurred.</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <description>This field stores the body of the response when the error occurred because of failed response.</description>
    <label>Response Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <description>This field stores the status code of the response when the error occurred because of failed response.</description>
    <label>Response Code</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>This field stores the stack trace for the exception that occurred.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field indicates whether the error occurred due to an exception in the code or a bad response.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Failed Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ErrorLogHandler.cls
//This class is written to create the custom error handling object record.
public class ErrorLogHandler{
    
    //This method logs error when the error is caused by Exception.
    public static void logError(String className, String methodName,  List<Id> recordIds, Exception ex) {
        List<Error_Log__c> loggerList = new List<Error_Log__c>();
        for(Id recordId : recordIds){
            Error_Log__c logger = new Error_Log__c();
            logger.Class_Name__c = className;
            logger.Method_Name__c = methodName;
            logger.Type__c = 'Exception';
            logger.Error_Message__c = ex.getMessage();
            logger.Stack_Trace__c = ex.getStackTraceString();
            logger.Line_Number__c = ex.getLineNumber();
            logger.Record_Id__c = recordId;
            loggerList.add(logger); 
        }
        insert loggerList;
    }
    
    //This method logs error when the error is caused by a failed or unsuccessful response from NPS.
     public static void logError(String className, String methodName,  List<Id> recordIds, HttpResponse response) {
        List<Error_Log__c> loggerList = new List<Error_Log__c>();
        for(Id recordId : recordIds){
            Error_Log__c logger = new Error_Log__c();
            logger.Class_Name__c = className;
            logger.Method_Name__c = methodName;
            logger.Type__c = 'Failed Response';
            logger.Response_Body__c = response.getBody();
            logger.Response_Code__c = response.getStatusCode();
            logger.Record_Id__c = recordId;
            loggerList.add(logger);
        }
        insert loggerList;
    }
}