force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>The object is created to log the errors occured during future method or any such background operation. Although, this object is useful generally for all kind of error logging.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field stored the ID of the record which was being processed when the error occurred.</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field indicates whether the error occurred due to an exception in the code or a bad response.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Failed Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ErrorLogHandlerTest.cls
@isTest
public class ErrorLogHandlerTest{

    //This data is created here only to pass record Ids of any object to the ErrorLogHandler methods since it can't be null
    @testSetup
    static void createRecordsForIds(){
        Account acc = new Account(Name = 'Test Account');
        insert acc; 
    }

    @isTest
    static void testLogErrorException(){
        try{
            Integer y = 0/0;
         }catch(Exception ex){
             List<Id> idList = new List<Id>();
             idList.add( [SELECT Id FROM Account].get(0).Id);
             ErrorLogHandler.logError('ErrorLogHandlerTest','testLogErrorException', idList , ex);
             System.assertEquals(1, [SELECT Record_Id__c, Type__c FROM Error_Log__c WHERE Type__c = 'Exception' ].size() );
         }  
    }
    
    @isTest
    static void testLogErrorResponse(){
        HttpResponse response = new NPSHttpCalloutMock().respondWithCode(new HTTPRequest(), 400);
        List<Id> idList = new List<Id>();
        idList.add( [SELECT Id FROM Account].get(0).Id);
        ErrorLogHandler.logError('ErrorLogHandlerTest','testLogErrorResponse', idList , response);
        System.assertEquals(1, [SELECT Record_Id__c, Type__c FROM Error_Log__c WHERE Type__c = 'Failed Response' ].size() );
    }
    
}